name: motorsaving
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - alabaster=1.0.0
  - alsa-lib=1.2.8
  - argon2-cffi=23.1.0
  - argon2-cffi-bindings=21.2.0
  - arrow=1.3.0
  - astroid=3.3.8
  - asttokens=2.4.1
  - async_generator=1.10
  - atomicwrites=1.4.1
  - attr=2.5.1
  - attrs=23.1.0
  - autopep8=2.0.4
  - backcall=0.2.0
  - backports=1.0
  - backports.tarfile=1.2.0
  - beautifulsoup4=4.12.2
  - binaryornot=0.4.4
  - black=25.1.0
  - blas=2.120
  - blas-devel=3.9.0
  - bleach=6.1.0
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - ca-certificates=2025.1.31
  - cairo=1.16.0
  - certifi=2024.12.14
  - cffi=1.16.0
  - chardet=5.2.0
  - click=8.1.8
  - cloudpickle=3.1.1
  - colorama=0.4.6
  - comm=0.1.4
  - contourpy=1.2.0
  - cookiecutter=2.6.0
  - cryptography=42.0.2
  - cycler=0.12.1
  - dbus=1.13.6
  - decorator=5.1.1
  - defusedxml=0.7.1
  - diff-match-patch=20241021
  - dill=0.3.9
  - docstring-to-markdown=0.15
  - docutils=0.21.2
  - entrypoints=0.4
  - exceptiongroup=1.2.0
  - executing=2.0.1
  - expat=2.5.0
  - fftw=3.3.10
  - flake8=7.1.1
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.46.0
  - freetype=2.12.1
  - gettext=0.21.1
  - giflib=5.2.1
  - glib=2.78.3
  - glib-tools=2.78.3
  - gmp=6.3.0
  - graphite2=1.3.13
  - gst-plugins-base=1.22.0
  - gstreamer=1.22.0
  - gstreamer-orc=0.4.34
  - h2=4.2.0
  - harfbuzz=6.0.0
  - hpack=4.1.0
  - hyperframe=6.1.0
  - icu=70.1
  - imagesize=1.4.1
  - importlib-metadata=7.0.0
  - importlib_metadata=7.0.0
  - importlib_resources=6.1.1
  - inflection=0.5.1
  - intervaltree=3.1.0
  - ipympl=0.9.3
  - ipython=8.18.1
  - ipython_genutils=0.2.0
  - ipywidgets=8.1.1
  - isort=6.0.0
  - jack=1.9.22
  - jaraco.classes=3.4.0
  - jaraco.context=6.0.1
  - jaraco.functools=4.1.0
  - jedi=0.18.1
  - jeepney=0.8.0
  - jellyfish=1.1.0
  - jinja2=3.1.2
  - jpeg=9e
  - jsonschema=4.20.0
  - jsonschema-specifications=2023.11.2
  - keyring=25.6.0
  - keyutils=1.6.1
  - kiwisolver=1.4.5
  - krb5=1.20.1
  - lame=3.100
  - lazy-object-proxy=1.6.0
  - lcms2=2.15
  - ld_impl_linux-64=2.40
  - lerc=4.0.0
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcap=2.67
  - libcblas=3.9.0
  - libclang=15.0.7
  - libclang13=15.0.7
  - libcups=2.3.3
  - libdb=6.2.32
  - libdeflate=1.17
  - libedit=3.1.20191231
  - libevent=2.1.10
  - libexpat=2.5.0
  - libffi=3.4.2
  - libflac=1.4.3
  - libgcc-ng=13.2.0
  - libgcrypt=1.10.3
  - libgfortran-ng=13.2.0
  - libgfortran5=13.2.0
  - libglib=2.78.3
  - libgpg-error=1.47
  - libhwloc=2.9.1
  - libiconv=1.17
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - libllvm15=15.0.7
  - libnsl=2.0.1
  - libogg=1.3.4
  - libopenblas=0.3.25
  - libopus=1.3.1
  - libpng=1.6.39
  - libpq=15.3
  - libsndfile=1.2.2
  - libsodium=1.0.18
  - libspatialindex=2.0.0
  - libsqlite=3.44.2
  - libstdcxx-ng=13.2.0
  - libsystemd0=253
  - libtiff=4.5.0
  - libtool=2.4.7
  - libudev1=253
  - libuuid=2.38.1
  - libuv=1.46.0
  - libvorbis=1.3.7
  - libwebp=1.3.2
  - libwebp-base=1.3.2
  - libxcb=1.13
  - libxkbcommon=1.5.0
  - libxml2=2.10.3
  - libzlib=1.2.13
  - llvm-openmp=17.0.6
  - lz4-c=1.9.4
  - markdown-it-py=3.0.0
  - markupsafe=2.1.3
  - mccabe=0.7.0
  - mdurl=0.1.2
  - mistune=3.0.2
  - mkl-service=2.4.0
  - mkl_fft=1.3.8
  - mkl_random=1.2.4
  - more-itertools=10.6.0
  - mpg123=1.32.3
  - munkres=1.1.4
  - mypy_extensions=1.0.0
  - mysql-common=8.0.33
  - mysql-libs=8.0.33
  - nbconvert=7.12.0
  - nbconvert-core=7.12.0
  - nbconvert-pandoc=7.12.0
  - nbformat=5.9.2
  - ncurses=6.4
  - nest-asyncio=1.5.8
  - nodejs=12.4.0
  - nspr=4.35
  - nss=3.95
  - numpy=1.26.2
  - numpy-base=1.26.2
  - numpydoc=1.8.0
  - olefile=0.47
  - openblas=0.3.25
  - openjpeg=2.5.0
  - openssl=3.1.6
  - packaging=23.2
  - pandoc=3.1.3
  - pandocfilters=1.5.0
  - parso=0.8.3
  - pathspec=0.12.1
  - pcre=8.45
  - pcre2=10.42
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pip=23.3.1
  - pixman=0.42.2
  - pkgutil-resolve-name=1.3.10
  - platformdirs=4.1.0
  - pluggy=1.5.0
  - ply=3.11
  - prometheus_client=0.19.0
  - prompt-toolkit=3.0.41
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pulseaudio=16.1
  - pulseaudio-client=16.1
  - pulseaudio-daemon=16.1
  - pure_eval=0.2.2
  - pycodestyle=2.12.1
  - pycparser=2.21
  - pydocstyle=6.3.0
  - pyflakes=3.2.0
  - pygments=2.17.2
  - pylint=3.3.4
  - pylint-venv=3.0.4
  - pyls-spyder=0.4.0
  - pyparsing=3.1.1
  - pyqt=5.15.9
  - pyqt5-sip=12.12.2
  - pyqtwebengine=5.15.9
  - pyrsistent=0.20.0
  - pysocks=1.7.1
  - python=3.11.6
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.19.0
  - python-lsp-black=2.0.0
  - python-lsp-jsonrpc=1.1.2
  - python-lsp-server=1.12.2
  - python-lsp-server-base=1.12.2
  - python-slugify=8.0.4
  - python-tzdata=2023.3
  - python_abi=3.11
  - pytoolconfig=1.2.5
  - pytz=2023.3.post1
  - pyxdg=0.28
  - pyyaml=6.0.2
  - pyzmq=25.1.2
  - qdarkstyle=3.2.3
  - qstylizer=0.2.4
  - qt=5.15.8
  - qt-main=5.15.8
  - qt-webengine=5.15.8
  - qtawesome=1.3.1
  - qtconsole=5.5.2
  - qtconsole-base=5.5.2
  - qtpy=2.4.2
  - readline=8.2
  - referencing=0.32.0
  - requests=2.32.3
  - rich=13.9.4
  - rope=1.13.0
  - rpds-py=0.13.2
  - rtree=1.3.0
  - secretstorage=3.3.3
  - send2trash=1.8.2
  - setuptools=68.2.2
  - sip=6.7.12
  - six=1.16.0
  - snowballstemmer=2.2.0
  - sortedcontainers=2.4.0
  - soupsieve=2.5
  - sphinx=8.1.3
  - sphinxcontrib-applehelp=2.0.0
  - sphinxcontrib-devhelp=2.0.0
  - sphinxcontrib-htmlhelp=2.1.0
  - sphinxcontrib-jsmath=1.0.1
  - sphinxcontrib-qthelp=2.0.0
  - sphinxcontrib-serializinghtml=1.1.10
  - sqlite=3.44.2
  - stack_data=0.6.2
  - tabulate=0.9.0
  - testpath=0.6.0
  - text-unidecode=1.3
  - textdistance=4.6.3
  - three-merge=0.1.1
  - tinycss2=1.2.1
  - tk=8.6.13
  - toml=0.10.2
  - tomli=2.0.1
  - tomlkit=0.13.2
  - tornado=6.3.3
  - traitlets=5.14.0
  - typing-extensions=4.9.0
  - typing_extensions=4.9.0
  - tzdata=2023c
  - ujson=5.10.0
  - watchdog=6.0.0
  - wcwidth=0.2.12
  - webencodings=0.5.1
  - whatthepatch=1.0.7
  - wheel=0.42.0
  - widgetsnbextension=4.0.9
  - wurlitzer=3.0.2
  - xcb-util=0.4.0
  - xcb-util-image=0.4.0
  - xcb-util-keysyms=0.4.0
  - xcb-util-renderutil=0.3.9
  - xcb-util-wm=0.4.1
  - xkeyboard-config=2.38
  - xorg-kbproto=1.0.7
  - xorg-libice=1.1.1
  - xorg-libsm=1.2.4
  - xorg-libx11=1.8.4
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxrender=0.9.10
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.2.6
  - yaml=0.2.5
  - yapf=0.43.0
  - zeromq=4.3.5
  - zipp=3.17.0
  - zlib=1.2.13
  - zstandard=0.22.0
  - zstd=1.5.5
  - pip:
      - anyio==4.1.0
      - apptools==5.3.0
      - arch==7.2.0
      - arviz==0.20.0
      - async-lru==2.0.4
      - babel==2.13.1
      - bambi==0.15.0
      - bctpy==0.6.1
      - biopython==1.83
      - brainspace==0.1.10
      - cachetools==5.5.1
      - charset-normalizer==3.3.2
      - cmasher==1.9.2
      - cognitiveatlas==0.1.9
      - colorspacious==1.1.2
      - cons==0.4.6
      - cython==3.0.8
      - dask==2025.1.0
      - dcor==0.6
      - debugpy==1.8.0
      - e13tools==0.9.6
      - envisage==7.0.3
      - et-xmlfile==2.0.0
      - etuples==0.3.9
      - fdasrsf==2.5.7
      - filelock==3.17.0
      - findiff==0.10.0
      - formulae==0.5.4
      - fqdn==1.5.1
      - fsspec==2024.12.0
      - future==1.0.0
      - fuzzywuzzy==0.18.0
      - graphviz==0.20.3
      - h5netcdf==1.4.1
      - h5py==3.10.0
      - hmmlearn==0.3.3
      - idna==3.6
      - imageio==2.34.0
      - intel-cmplr-lib-ur==2025.0.3
      - intel-openmp==2025.0.3
      - ipykernel==6.27.1
      - isoduration==20.11.0
      - joblib==1.3.2
      - json5==0.9.14
      - jsonpointer==2.4
      - lazy-loader==0.3
      - littleutils==0.2.2
      - llvmlite==0.41.1
      - load-confounds==0.12.0
      - locket==1.0.0
      - logical-unification==0.4.6
      - lxml==4.9.3
      - matplotlib==3.10.1
      - matplotlib-inline==0.1.7
      - mayavi==4.8.2
      - mgarch==0.3.0
      - minikanren==1.0.3
      - mkl==2025.0.1
      - mpmath==1.3.0
      - multidict==6.0.5
      - multimethod==1.10
      - multipledispatch==1.0.0
      - natsort==8.4.0
      - nbclassic==1.0.0
      - nbclient==0.9.0
      - netneurotools==0.2.4
      - networkx==3.2.1
      - neuromaps==0.0.5
      - nibabel==5.2.0
      - nilearn==0.10.2
      - nimare
      - numba==0.58.1
      - openpyxl==3.1.5
      - outdated==0.2.2
      - overrides==7.4.0
      - palettable==3.3.3
      - pandarallel==1.6.5
      - pandas==2.2.1
      - pandas-flavor==0.6.0
      - partd==1.4.2
      - patsy==0.5.4
      - pillow==10.1.0
      - pingouin==0.5.5
      - psutil==5.9.6
      - pyarrow==19.0.0
      - pyface==8.0.0
      - pymare==0.0.4rc2
      - pymc==5.20.0
      - pynndescent==0.5.11
      - pyriemann==0.6
      - pysurfer
      - pytensor==2.26.4
      - python-json-logger==2.0.7
      - rdata==0.10.0
      - retrying==1.3.4
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - ridgeplot==0.1.24
      - rsatoolbox==0.1.5
      - scikit-datasets==0.2.4
      - scikit-fda==0.9
      - scikit-image==0.22.0
      - scikit-learn==1.5.1
      - scipy==1.11.4
      - seaborn==0.13.2
      - sniffio==1.3.0
      - sparse==0.15.1
      - statsmodels==0.14.0
      - style==1.1.0
      - surfplot==0.2.0
      - swifter==1.4.0
      - sympy==1.12
      - tbb==2022.0.0
      - tcmlib==1.2.0
      - tenacity==8.2.3
      - terminado==0.18.0
      - threadpoolctl==3.2.0
      - tifffile==2024.2.12
      - toolz==1.0.0
      - tqdm==4.66.1
      - traits==6.4.3
      - traitsui==8.0.0
      - types-python-dateutil==2.8.19.14
      - umap-learn==0.5.5
      - umf==0.9.1
      - update==0.0.1
      - uri-template==1.3.0
      - urllib3==2.1.0
      - vtk==9.3.0
      - webcolors==1.13
      - websocket-client==1.7.0
      - wordcloud==1.9.3
      - xarray==2023.12.0
      - xarray-einstats==0.8.0

